// This file is generated by rust-protobuf 2.8.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `tensorflow_serving/config/log_collector_config.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_1;

#[derive(PartialEq,Clone,Default)]
pub struct LogCollectorConfig {
    // message fields
    pub field_type: ::std::string::String,
    pub filename_prefix: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a LogCollectorConfig {
    fn default() -> &'a LogCollectorConfig {
        <LogCollectorConfig as ::protobuf::Message>::default_instance()
    }
}

impl LogCollectorConfig {
    pub fn new() -> LogCollectorConfig {
        ::std::default::Default::default()
    }

    // string type = 1;


    pub fn get_field_type(&self) -> &str {
        &self.field_type
    }
    pub fn clear_field_type(&mut self) {
        self.field_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: ::std::string::String) {
        self.field_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_field_type(&mut self) -> &mut ::std::string::String {
        &mut self.field_type
    }

    // Take field
    pub fn take_field_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.field_type, ::std::string::String::new())
    }

    // string filename_prefix = 2;


    pub fn get_filename_prefix(&self) -> &str {
        &self.filename_prefix
    }
    pub fn clear_filename_prefix(&mut self) {
        self.filename_prefix.clear();
    }

    // Param is passed by value, moved
    pub fn set_filename_prefix(&mut self, v: ::std::string::String) {
        self.filename_prefix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filename_prefix(&mut self) -> &mut ::std::string::String {
        &mut self.filename_prefix
    }

    // Take field
    pub fn take_filename_prefix(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filename_prefix, ::std::string::String::new())
    }
}

impl ::protobuf::Message for LogCollectorConfig {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.field_type)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filename_prefix)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.field_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.field_type);
        }
        if !self.filename_prefix.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.filename_prefix);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.field_type.is_empty() {
            os.write_string(1, &self.field_type)?;
        }
        if !self.filename_prefix.is_empty() {
            os.write_string(2, &self.filename_prefix)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> LogCollectorConfig {
        LogCollectorConfig::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "type",
                    |m: &LogCollectorConfig| { &m.field_type },
                    |m: &mut LogCollectorConfig| { &mut m.field_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "filename_prefix",
                    |m: &LogCollectorConfig| { &m.filename_prefix },
                    |m: &mut LogCollectorConfig| { &mut m.filename_prefix },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<LogCollectorConfig>(
                    "LogCollectorConfig",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static LogCollectorConfig {
        static mut instance: ::protobuf::lazy::Lazy<LogCollectorConfig> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const LogCollectorConfig,
        };
        unsafe {
            instance.get(LogCollectorConfig::new)
        }
    }
}

impl ::protobuf::Clear for LogCollectorConfig {
    fn clear(&mut self) {
        self.field_type.clear();
        self.filename_prefix.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for LogCollectorConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LogCollectorConfig {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n4tensorflow_serving/config/log_collector_config.proto\x12\x12tensorflo\
    w.serving\"Q\n\x12LogCollectorConfig\x12\x12\n\x04type\x18\x01\x20\x01(\
    \tR\x04type\x12'\n\x0ffilename_prefix\x18\x02\x20\x01(\tR\x0efilenamePre\
    fixB\x03\xf8\x01\x01J\xb9\x02\n\x06\x12\x04\0\0\x0b\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x1b\n\x08\n\x01\x08\x12\
    \x03\x03\0\x1f\n\t\n\x02\x08\x1f\x12\x03\x03\0\x1f\n\n\n\x02\x04\0\x12\
    \x04\x05\0\x0b\x01\n\n\n\x03\x04\0\x01\x12\x03\x05\x08\x1a\nY\n\x04\x04\
    \0\x02\0\x12\x03\x07\x02\x12\x1aL\x20Identifies\x20the\x20type\x20of\x20\
    the\x20LogCollector\x20we\x20will\x20use\x20to\x20collect\x20these\x20lo\
    gs.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x07\x02\x08\n\x0c\n\x05\x04\0\
    \x02\0\x01\x12\x03\x07\t\r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x07\x10\
    \x11\n?\n\x04\x04\0\x02\x01\x12\x03\n\x02\x1d\x1a2\x20The\x20prefix\x20t\
    o\x20use\x20for\x20the\x20filenames\x20of\x20the\x20logs.\n\n\x0c\n\x05\
    \x04\0\x02\x01\x05\x12\x03\n\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\
    \x03\n\t\x18\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\n\x1b\x1cb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
